/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
    "./src/lib/**/*.{js,ts,jsx,tsx}",
    "./src/stores/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "var(--color-primary-50, #EFF6FF)",
          100: "var(--color-primary-100, #DBEAFE)",
          200: "var(--color-primary-200, #BFDBFE)",
          300: "var(--color-primary-300, #93C5FD)",
          400: "var(--color-primary-400, #60A5FA)",
          500: "var(--color-primary-500, #3B82F6)",
          600: "var(--color-primary-600, #2563EB)",
          700: "var(--color-primary-700, #1D4ED8)",
          800: "var(--color-primary-800, #1E40AF)",
          900: "var(--color-primary-900, #1E3A8A)",
          950: "var(--color-primary-950, #172554)",
          DEFAULT: "var(--color-primary-default, #001387)",
        },
        "rodri-primary": "#4fad33",
        "rodri-primary-dark": "#3d8f29",
        "rodri-primary-glow": "#4fad33",
        "rodri-accent": "#84cc16",
        "rodri-charcoal": "#0f172a",
        "rodri-charcoal-foreground": "#f8fafc",
        "rodri-muted": "#64748b",
        "rodri-muted-foreground": "#64748b",
        "rodri-foreground": "#0f172a",
        "rodri-background": "#ffffff",
        "rodri-card": "#ffffff",
        "rodri-secondary": "#f8fafc",
        "rodri-border": "#e2e8f0",
        "rodri-input": "#e2e8f0",
        "rodri-primary-foreground": "#ffffff",
        "tertiary-container": "var(--color-tertiary-container, #820801)",
        "on-primary-container": "var(--color-on-primary-container, #98a3ff)",
        "on-surface-variant": "var(--color-on-surface-variant, #444655)",
        "surface-container-high": "var(--color-surface-container-high, #e2e7ff)",
        "primary-container": "var(--color-primary-container, #0020c2)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #241a00)",
        "tertiary": "var(--color-tertiary, #590300)",
        "surface": "var(--color-surface, #faf8ff)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #ff8875)",
        "on-error": "var(--color-on-error, #ffffff)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #8e1307)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #bcc2ff)",
        "primary-fixed": "var(--color-primary-fixed, #dfe0ff)",
        "surface-variant": "var(--color-surface-variant, #dae2fd)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "inverse-surface": "var(--color-inverse-surface, #283044)",
        "surface-bright": "var(--color-surface-bright, #faf8ff)",
        "error-container": "var(--color-error-container, #ffdad6)",
        "secondary-fixed": "var(--color-secondary-fixed, #ffe088)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #eef0ff)",
        "outline": "var(--color-outline, #757687)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #e9c349)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #000b62)",
        "inverse-primary": "var(--color-inverse-primary, #bcc2ff)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #ffb4a7)",
        "surface-container-low": "var(--color-surface-container-low, #f2f3ff)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "error": "var(--color-error, #ba1a1a)",
        "secondary-container": "var(--color-secondary-container, #fed65b)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #152dc9)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #ffdad4)",
        "surface-container": "var(--color-surface-container, #eaedff)",
        "outline-variant": "var(--color-outline-variant, #c5c5d8)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #574500)",
        "surface-tint": "var(--color-surface-tint, #374be0)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #400100)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "surface-dim": "var(--color-surface-dim, #d2d9f4)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "background": "var(--color-background, #faf8ff)",
        "on-background": "var(--color-on-background, #131b2e)",
        "surface-container-highest": "var(--color-surface-container-highest, #dae2fd)",
        "on-secondary-container": "var(--color-on-secondary-container, #745c00)",
        "secondary": "var(--color-secondary, #735c00)",
        "on-surface": "var(--color-on-surface, #131b2e)",
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-padding": "80px",
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
      },
      fontFamily: {
        "headline-md": ["var(--font-headline-md, 'Inter')"],
        "headline-lg": ["var(--font-headline-lg, 'Inter')"],
        "headline-lg-mobile": ["var(--font-headline-lg-mobile, 'Inter')"],
        "headline-display": ["var(--font-headline-display, 'Inter')"],
        "body-md": ["var(--font-body-md, 'Inter')"],
        "body-lg": ["var(--font-body-lg, 'Inter')"],
        "label-sm": ["var(--font-label-sm, 'Inter')"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
  ],
};
