export const PERMISSIONS = {
  SITE_CREATE: "site.create",
  SITE_READ: "site.read",
  SITE_UPDATE: "site.update",
  SITE_DELETE: "site.delete",
  SITE_PUBLISH: "site.publish",
  USER_CREATE: "user.create",
  USER_READ: "user.read",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",
  USER_INVITE: "user.invite",
  ROLE_MANAGE: "role.manage",
  BILLING_MANAGE: "billing.manage",
  BILLING_READ: "billing.read",
  SUBSCRIPTION_MANAGE: "subscription.manage",
  SUBSCRIPTION_READ: "subscription.read",
  ANALYTICS_VIEW: "analytics.view",
  ANALYTICS_EXPORT: "analytics.export",
  LEAD_CREATE: "lead.create",
  LEAD_READ: "lead.read",
  LEAD_UPDATE: "lead.update",
  LEAD_EXPORT: "lead.export",
  INTEGRATION_MANAGE: "integration.manage",
  CONFIG_TENANT: "config.tenant",
  CONFIG_SYSTEM: "config.system",
  AUDIT_VIEW: "audit.view",
  TEMPLATE_MANAGE: "template.manage",
  PLAN_MANAGE: "plan.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  SUPPORT: "support",
  OWNER: "owner",
  ADMIN: "admin",
  EDITOR: "editor",
  MARKETING: "marketing",
  BILLING: "billing",
  VIEWER: "viewer",
} as const;

export type RoleSlug = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<RoleSlug, string[]> = {
  super_admin: Object.values(PERMISSIONS),
  support: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.SUBSCRIPTION_READ,
  ],
  owner: [
    PERMISSIONS.SITE_CREATE,
    PERMISSIONS.SITE_READ,
    PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.SITE_DELETE,
    PERMISSIONS.SITE_PUBLISH,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.INTEGRATION_MANAGE,
    PERMISSIONS.CONFIG_TENANT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  admin: [
    PERMISSIONS.SITE_CREATE,
    PERMISSIONS.SITE_READ,
    PERMISSIONS.SITE_UPDATE,
    PERMISSIONS.SITE_PUBLISH,
    PERMISSIONS.USER_READ,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.CONFIG_TENANT,
    PERMISSIONS.INTEGRATION_MANAGE,
  ],
  editor: [
    PERMISSIONS.SITE_READ,
    PERMISSIONS.SITE_UPDATE,
  ],
  marketing: [
    PERMISSIONS.SITE_READ,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_EXPORT,
    PERMISSIONS.INTEGRATION_MANAGE,
  ],
  billing: [
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.SUBSCRIPTION_READ,
  ],
  viewer: [
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.LEAD_READ,
  ],
};

export const DEFAULT_PLANS = [
  {
    name: "Free",
    slug: "free",
    price: 0,
    maxUsers: 1,
    maxSites: 1,
    maxStorage: 50 * 1024 * 1024,
    features: ["1 sitio web", "Subdominio", "Editor visual", "Formulario de contacto", "Analytics básicos"],
  },
  {
    name: "Pro",
    slug: "pro",
    price: 29.99,
    maxUsers: 3,
    maxSites: 3,
    maxStorage: 500 * 1024 * 1024,
    features: ["3 sitios web", "Dominio personalizado", "SEO avanzado", "Formularios ilimitados", "Exportación leads", "Integración WhatsApp", "Google Analytics", "Facebook Pixel"],
  },
  {
    name: "Business",
    slug: "business",
    price: 79.99,
    maxUsers: 10,
    maxSites: 10,
    maxStorage: 5 * 1024 * 1024 * 1024,
    features: ["10 sitios web", "Dominio personalizado", "SEO avanzado", "Roles avanzados", "API pública", "Webhooks", "Soporte prioritario", "White-label"],
  },
] as const;
